### ISSUE TITLE
Member Access into incomplete type 'Sound Player'

### ISSUE THREAD

**Issue by coltonboyd503** [LaurentGomila/SFML-Game-Development-Book#11]
Line 10 of SoundNode.cpp

**Comment by Bromeon** [comment]
[Line 10 of SoundNode.cpp](https://github.com/SFML/SFML-Game-Development-Book/blob/master/10_Network/Source/SoundNode.cpp#L10) is empty. Also, `SoundPlayer.hpp` is included in that file, so the type is known at this point. It might be an issue with your setup.
