### ISSUE TITLE
CMake script broken for SFML >= 2.5

### ISSUE THREAD

**Issue by copyrat90** [LaurentGomila/SFML-Game-Development-Book#12]
As [`${SFML_LIBRARIES}`, `${SFML_DEPENDENCIES}` and `${SFML_INCLUDE_DIR}` were removed](https://en.sfml-dev.org/forums/index.php?topic=24070.0) from SFML after v2.5,
you can't build the example as-is, on the latest stable version.

I had to do some workaround on my fork (https://github.com/copyrat90/SFML-Game-Development-Book/commit/928f347be756e2aad827498f9fea7d6fb07d7cba), in order to build it properly.

It would be nice if you can build the example without messing around the CMake script.

**Comment by copyrat90** [comment]
Sorry, my bad, I was using the SFML master branch, without knowing it is a version 3.
After switching to a 2.6.x branch and building, it works fine.

**Comment by eXpl0it3r** [comment]
Ah okay. Yeah, the book code won't be updated for SFML 3 🙂
