### ISSUE TITLE
No virtual destructor in SceneNode

### ISSUE THREAD

**Issue by some-mthfka** [LaurentGomila/SFML-Game-Development-Book#6]
No SceneNode class contains a virtual destructor declaration, while it is a base class with many other virtual functions. I suppose it is a bug, causing memory leaks.

**Comment by Bromeon** [comment]
You could have waited for the response [here](http://en.sfml-dev.org/forums/index.php?topic=20004) before opening an issue, because as mentioned, `SceneNode`'s base classes have virtual destructors.
